Stomp planner
ipa320/cob_manipulation pull request #104
Opened 2017-03-12 12:52 UTC by ipa-bfb

Same as requested in cob_robots

2017-03-13 07:49 UTC, fmessmer requested changes
Please review your PR for formal correctness before we can review the actual feature:
 - do not change indentation scheme
 - revert moving files
 - do not add unintended files
 - reference/link related PRs

2017-03-13 07:59 UTC, fmessmer requested changes

2017-03-13 07:59 UTC, ipa-fxm commented on cob_kinematics/ikfast/plugins.xml
> +</class_libraries>
you need to be cautious when using `git add -a` or `git commit -a`...I do not recommend it....
remove this file...

2017-03-13 07:59 UTC, ipa-fxm commented on cob_moveit_bringup/launch/move_group.launch
> +  <arg name="load_robot_description" default="true"/>
do not change default behavior!

2017-03-13 07:59 UTC, ipa-fxm commented on cob_moveit_bringup/launch/move_group.launch
> +    <arg name="moveit_controller_manager" value="fake" if="$(arg fake_execution)"/>
`if` condition goes first...
also, fake_execution is only used in demo.launch...please remove

2017-03-13 07:59 UTC, ipa-fxm commented on cob_moveit_bringup/launch/move_group.launch
> +	<param name="collision_detector" value="IndustrialFCL" />
indentation

2017-03-13 07:59 UTC, ipa-fxm commented on cob_moveit_bringup/launch/move_group.launch
> +	<param name="collision_detector" value="IndustrialFCL" />
I guess people wanting to use this need to install some things....please add the package for `IndustrialFCL` to the package.xml

2017-03-13 07:59 UTC, ipa-fxm commented on cob_moveit_bringup/launch/moveit_ompl.rviz
>      Property Tree Widget:
do not commit changes to the rviz config files...keep your configuration local and uncommited
same below

2017-03-13 07:59 UTC, ipa-fxm commented on cob_moveit_bringup/launch/rviz.launch
> +  <arg     if="$(arg config)" name="command_args" value="-d $(find cob_moveit_bringup)/launch/moveit_$(arg pipeline).rviz" />
we could make the config arg to accept a filename...

2017-03-13 07:59 UTC, ipa-fxm commented on cob_moveit_bringup/launch/stomp_planning_pipeline.xml
> +  <arg name="planning_plugin" value="stomp_moveit/StompPlannerManager" />
add `stomp_moveit` as a dependency to the package.xml

2017-03-14 08:21 UTC, fmessmer requested changes
please remove the rviz configs as they are robot and scenario specific....keep them local only!

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/package.xml
> +  <exec_depend>stomp_moveit</exec_depend>
also add `moveit_ros_perception` as `occupancy_map_monitor` as it is used in cob_robots/cob_moveit_config sensors.yaml!

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/package.xml
> +  <exec_depend>IndustrialFCL</exec_depend>
IndustrialFCL is part of `industrial_collision_detection` which is not released...
what do you use it for?

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/package.xml
> +  <exec_depend>stomp_moveit</exec_depend>
also, please respect alphabetical order in package.xml

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/package.xml
> +  <exec_depend>stomp_moveit</exec_depend>
unfortunately, `stomp_moveit` seems not to be released as well...

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/launch/move_group.launch
> +    <arg name="moveit_controller_manager" value="fake" if="$(arg fake_execution)"/>
why do you need this?
isn't the line `<arg name="fake_execution" value="$(arg fake_execution)"/>` sufficient for fake_execution?

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/launch/move_group.launch
> +    <param name="collision_detector" value="IndustrialFCL" />
what does this do?

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/launch/ompl_rviz.launch
> +<launch>
remove this file...you need to load the proper config locally

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/launch/stomp_moveit.rviz
> +Panels:
remove this file...you need to load the proper config locally...it's a duplicate anyway...

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/launch/moveit_stomp.rviz
> +Panels:
remove this file...you need to load the proper config locally

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/launch/moveit_ompl.rviz
> +Panels:
remove this file...you need to load the proper config locally

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/launch/stomp_moveit_planning_pipeline.launch.xml
> +<launch>
stick to the naming scheme and call this file `stomp_planning_pipeline.xml` in analogy to ompl

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/launch/stomp_moveit_rviz.launch
> +<launch>
remove this file...you need to load the proper config locally...it's a duplicate anyway

2017-03-14 08:21 UTC, ipa-fxm commented on cob_moveit_bringup/launch/stomp_moveit_planning_pipeline.launch.xml
> +<launch>
remove this file...the required `stomp_planning_pipeline.xml` is part of this PR below

2017-03-14 08:23 UTC, ipa-fxm commented
We have some significant dependency trouble for this feature as they do not seem to be released!

Could you post what additional packages you use in your workspace, i.e.
 - moveit from source? which branch?
 - industrial_moveit from source?
 - stomp? which repo?

2017-03-14 12:40 UTC, ipa-bfb commented on cob_moveit_bringup/launch/move_group.launch
> +    <param name="collision_detector" value="IndustrialFCL" />
We need it for stomp....

2017-03-16 09:57 UTC, ipa-bfb commented
I used this one:

http://wiki.ros.org/industrial_moveit

https://github.com/ros-industrial/industrial_moveit

2017-03-22 11:48 UTC, ipa-fxm commented
@ipa-bfb 
unfortunately, it still does not pass Travis CI tests...

2017-03-22 11:52 UTC, ipa-bfb commented
We are close to get it ;)

2017-03-25 10:01 UTC, ipa-fxm commented
maybe it's because `stomp_core` has not [install tags](https://github.com/ros-industrial/industrial_moveit/blob/indigo-devel/stomp_core/CMakeLists.txt#L47-L51)

2017-03-27 09:53 UTC, ipa-bfb commented
How should I proceed?

2017-03-27 11:12 UTC, mathias-luedtke commented
> How should I proceed?

Add the install and open a PR. Or at least open an issue for pointing it out.

2017-03-28 20:57 UTC, ipa-fxm commented
Well, you could create a fork of `industrial_moveit` and temporarily use the uri of your fork within the .rosinstall file...then apply fixes/changes until Travis CI passes...
Then you create a PR back to ros-industrial with the changes in your fork...asking to be merged and released...

2017-03-29 08:08 UTC, ipa-bfb commented
Yes that is a cool idea. I am without computer till Friday but on friday and after the help ipa-mdl i think I can do it tomorrow ;)

2017-03-30 12:00 UTC, ipa-bfb commented
Awesome it worked ;) should I make a pull request to them now? Best,
Bruno

2017-04-04 15:41 UTC, ipa-fxm commented on .travis.rosinstall
>      version: cmake_install_tags
change back the `version` as well

2017-04-04 15:42 UTC, fmessmer requested changes

2017-04-04 15:42 UTC, ipa-fxm commented on cob_moveit_bringup/launch/move_group.launch
> +    <param name="collision_detector" value="IndustrialFCL" />
@ipa-bfb 
what package is this plugin(?) provided in?

2017-04-05 09:06 UTC, ipa-bfb commented
Is provided here:

https://github.com/ros-industrial/industrial_moveit/tree/indigo-devel/industrial_collision_detection

It is part of industrial moveit but it can also be installed directly:

sudo apt-get install ros-indigo-industrial-collision-detection

2017-04-05 09:30 UTC, fmessmer requested changes

2017-04-05 09:30 UTC, ipa-fxm commented on cob_moveit_bringup/launch/move_group.launch
> +    <param name="collision_detector" value="IndustrialFCL" />
it's defined in https://github.com/ros-industrial/industrial_moveit/blob/indigo-devel/industrial_collision_detection/industrial_collision_detection_plugin_description.xml
so we need a `<exec_depend>industrial_collision_detection</exec_depend>`

2017-04-05 09:30 UTC, ipa-fxm commented on cob_moveit_bringup/launch/move_group.launch
> +
remove blank line

2017-04-05 09:30 UTC, ipa-fxm commented on cob_moveit_bringup/launch/move_group.launch
> +    <arg name="config_path" value="$(arg config_path)"/>
restore previous order

2017-04-05 09:30 UTC, ipa-fxm commented on cob_moveit_bringup/launch/stomp_moveit_planning_pipeline.xml
> +<launch>
remove this file and use `stomp_planning_pipeline.xml` instead

2017-04-05 09:30 UTC, ipa-fxm commented on cob_moveit_bringup/launch/stomp_planning_pipeline.xml
> +<launch>
make consistent with `ompl_planning_pipeline.xml`

2017-04-05 09:30 UTC, ipa-fxm commented on cob_moveit_bringup/package.xml
> +  <exec_depend>moveit_ros_perception</exec_depend>
remove this - is duplicate

2017-04-05 09:30 UTC, ipa-fxm commented on cob_moveit_bringup/package.xml
>    <exec_depend>cob_moveit_config</exec_depend>
add `<exec_depend>industrial_collision_detection</exec_depend>`

2017-04-05 09:30 UTC, ipa-fxm commented on cob_moveit_bringup/package.xml
>    <exec_depend>robot_state_publisher</exec_depend>
add `<exec_depend>stomp_moveit</exec_depend>`

2017-04-05 14:21 UTC, fmessmer approved these changes

2017-04-05 16:19 UTC, merged