Adding chomp planning pipeline
ipa320/cob_manipulation pull request #113
Opened 2017-04-26 08:12 UTC by patelmayank2092

2017-04-27 16:09 UTC, fmessmer requested changes

2017-04-27 16:09 UTC, ipa-fxm commented on cob_moveit_bringup/launch/chomp_planning_pipeline.xml
> +   <arg name="planning_plugin" value="chomp_interface/CHOMPPlanner" />
using `chomp_interface` would require to define an `<exec_depend>` to `chomp_interface`

@ipa-bfb 
is this package installable from debs?

2017-05-18 17:15 UTC, fmessmer approved these changes
thx

2017-05-18 17:15 UTC, merged

2017-05-19 14:18 UTC, ipa-mdl commented
Perhaps http://wiki.ros.org/chomp_motion_planner

2017-05-19 14:21 UTC, ipa-mdl commented on cob_manipulation/package.xml
> +  <exec_depend>moveit_planner_chomp</exec_depend>
The dependency was added to the meta-package..